const DATA_URL='data/growth-update-2026-08-25.json';let data={topics:[]};let currentFilter='all';
const $=s=>document.querySelector(s);
async function load(){try{const r=await fetch(DATA_URL+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Data unavailable');data=await r.json();render()}catch(e){$('#topics').innerHTML='<div class="glass topic" style="grid-column:1/-1"><h3>Growth data is not available yet.</h3><p>Research data could not be loaded.</p></div>';$('#updated').textContent='Data unavailable'}}
function render(){const topics=(data.topics||[]).filter(t=>currentFilter==='all'||t.category===currentFilter);$('#updated').textContent='Updated '+formatDate(data.updated_at);$('#year').textContent=new Date().getFullYear();$('#heroStats').innerHTML=`<div class="stat"><b>${data.topics?.length||0}</b><span>OPPORTUNITIES</span></div><div class="stat"><b>${data.topics?.[0]?.score||'—'}</b><span>TOP SCORE</span></div><div class="stat"><b>${data.research?.sources_count||'—'}</b><span>RESEARCH SOURCES</span></div>`;$('#topics').innerHTML=topics.map(card).join('');document.querySelectorAll('.topic').forEach(el=>el.addEventListener('click',()=>openTopic(Number(el.dataset.index))));}
function card(t){return `<article class="glass topic" data-index="${data.topics.indexOf(t)}"><span class="rank">#${t.rank||data.topics.indexOf(t)+1} · ${esc(t.category||'Tech')}</span><span class="score">${t.score||0}/100</span><h3>${esc(t.topic)}</h3><p>${esc(t.why_make||'High-potential topic for the channel.')}</p><div class="chips"><span class="chip">Demand ${t.demand||'—'}</span><span class="chip">Competition ${t.competition||'—'}</span><span class="chip">Fit ${t.channel_fit||'—'}</span></div><button class="open">View full package</button></article>`}
function openTopic(i){const t=data.topics[i];if(!t)return;const titles=(t.titles||[]).map(x=>`• ${esc(x)}`).join('\n');const tags=(t.tags||[]).join(', ');const hash=(t.hashtags||[]).join(' ');$('#modalContent').innerHTML=`<span class="eyebrow">#${t.rank||i+1} · ${esc(t.category||'Tech')}</span><h2>${esc(t.topic)}</h2><p>${esc(t.why_make||'')}</p><h3>Recommended title</h3><pre>${esc(t.recommended_title||t.titles?.[0]||'')}</pre><h3>Alternative titles</h3><pre>${titles||'No alternatives yet.'}</pre><h3>Description</h3><pre>${esc(t.description||'')}</pre><h3>Tags</h3><pre>${esc(tags)}</pre><h3>Hashtags</h3><pre>${esc(hash)}</pre><h3>Thumbnail</h3><pre>${esc((t.thumbnail?.text||'')+'\n\n'+(t.thumbnail?.concept||'')+'\n\nPROMPT:\n'+(t.thumbnail?.prompt||''))}</pre><button class="copy" id="copyAll">Copy complete package</button>`;$('#copyAll').onclick=()=>navigator.clipboard?.writeText(packageText(t));$('#topicDialog').showModal()}
function packageText(t){return `TOPIC: ${t.topic}\nSCORE: ${t.score}/100\n\nRECOMMENDED TITLE:\n${t.recommended_title||t.titles?.[0]||''}\n\nTITLES:\n${(t.titles||[]).join('\n')}\n\nDESCRIPTION:\n${t.description||''}\n\nTAGS:\n${(t.tags||[]).join(', ')}\n\nHASHTAGS:\n${(t.hashtags||[]).join(' ')}\n\nTHUMBNAIL PROMPT:\n${t.thumbnail?.prompt||''}`}
function formatDate(v){if(!v)return'Unknown';const d=new Date(v);return isNaN(d)?v:d.toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()}));$('#closeDialog').onclick=()=>$('#topicDialog').close();$('#topicDialog').addEventListener('click',e=>{if(e.target===$('#topicDialog'))$('#topicDialog').close()});load();