const API='https://api.github.com/repos/LaxmanNepal/Videos/contents/course/youtube?ref=main';
const MEDIA='https://media.githubusercontent.com/media/LaxmanNepal/Videos/main/';
const $=s=>document.querySelector(s);
let lessons=[],current=-1;
const saved=()=>JSON.parse(localStorage.getItem('ln-course-progress')||'{}');
const save=p=>localStorage.setItem('ln-course-progress',JSON.stringify(p));
function clean(name){return name.replace(/\.mp4$/i,'').replace(/^\s*\d+[\s._-]*/,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim()}
function number(name){const m=name.match(/^\s*(\d+)/);return m?m[1]:''}
function mediaUrl(path){return MEDIA+path.split('/').map(encodeURIComponent).join('/')}
function progressStats(){const p=saved(),done=lessons.filter(x=>p[x.path]).length,pc=lessons.length?Math.round(done/lessons.length*100):0;$('#watchedCount').textContent=done;$('#percent').textContent=pc+'%';$('#progressText').textContent=pc+'% complete';return {done,pc}}
function render(){const q=$('#search').value.trim().toLowerCase();const list=lessons.filter(x=>x.title.toLowerCase().includes(q));$('#lessonList').innerHTML=list.length?list.map((x)=>{const i=lessons.indexOf(x),p=saved();return `<button class="lesson ${i===current?'active':''}" data-i="${i}"><span class="num">${number(x.name)||i+1}</span><span class="lesson-title">${escapeHtml(x.title)}</span><span class="check">${p[x.path]?'✓':''}</span></button>`}).join(''):`<div class="loading">No lessons found.</div>`;document.querySelectorAll('.lesson').forEach(b=>b.onclick=()=>openLesson(+b.dataset.i));$('#sidebarCount').textContent=lessons.length;$('#lessonCount').textContent=lessons.length;progressStats()}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openLesson(i,autoplay=true){if(!lessons[i])return;current=i;const x=lessons[i],v=$('#video');v.src=mediaUrl(x.path);v.hidden=false;$('#emptyPlayer').hidden=true;$('#lessonInfo').hidden=false;$('#lessonNumber').textContent=`LESSON ${number(x.name)||i+1}`;$('#lessonTitle').textContent=x.title;$('#lessonPath').textContent=x.name;$('#prevBtn').disabled=i===0;$('#nextBtn').disabled=i===lessons.length-1;render();window.scrollTo({top:0,behavior:'smooth'});if(autoplay)v.play().catch(()=>{});localStorage.setItem('ln-course-last',x.path);$('#continueTitle').textContent=x.title;$('#continueBtn').disabled=false}
function markDone(){if(current<0)return;const p=saved();p[lessons[current].path]=true;save(p);render()}
async function load(){const status=$('#status');status.textContent='Syncing…';try{const r=await fetch(API,{cache:'no-store'});if(!r.ok)throw new Error('GitHub API '+r.status);const files=await r.json();lessons=files.filter(x=>x.type==='file'&&/\.mp4$/i.test(x.name)).map(x=>({name:x.name,path:x.path,title:clean(x.name)})).sort((a,b)=>{const na=parseInt(a.name)||9999,nb=parseInt(b.name)||9999;return na-nb||a.name.localeCompare(b.name)});render();const last=localStorage.getItem('ln-course-last'),idx=lessons.findIndex(x=>x.path===last);if(idx>=0){$('#continueTitle').textContent=lessons[idx].title;$('#continueBtn').disabled=false;$('#continueBtn').onclick=()=>openLesson(idx)}else if(lessons[0]){$('#continueTitle').textContent=lessons[0].title;$('#continueBtn').disabled=false;$('#continueBtn').onclick=()=>openLesson(0)}status.textContent=`${lessons.length} lessons synced`;if(current>=0)openLesson(current,false)}catch(e){console.error(e);status.textContent='Could not sync lessons';$('#lessonList').innerHTML='<div class="loading">Could not load the video library. Check the repository visibility or try Refresh.</div>'}}
$('#search').addEventListener('input',render);$('#refreshBtn').onclick=load;$('#prevBtn').onclick=()=>openLesson(current-1);$('#nextBtn').onclick=()=>openLesson(current+1);$('#video').addEventListener('ended',()=>{markDone();if(current<lessons.length-1)openLesson(current+1,false)});$('#video').addEventListener('timeupdate',()=>{if($('#video').duration&&$('#video').currentTime/$('#video').duration>.85)markDone()});$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('ln-course-theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('ln-course-theme')==='light')document.body.classList.add('light');$('#year').textContent=new Date().getFullYear();load();